### ISSUE TITLE
metric method working for Dryad

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#10]
Get the metric method working all the way for Dryad, so that returns the contents expected by the api.  Fully and usefully tested.

**Comment by richard-jones** [comment]
I've disabled the metrics stuff in Dryad for the moment, as it was causing problems testing the backend.  It looks like the problem is that the URL being used to gather metrics is just the dx.doi.org/ url, rather than some api call, and it's not responding appropriately.  

I have disabled this by setting provides_metrics() to return False for the time being

**Comment by hpiwowar** [comment]
I think the metrics item is working... if it breaks on something please do open another issue.

The Dryad api doesn't include metrics, so we have permission to screen scrape for them.  

Set provides_metrics() to return True again.
