### ISSUE TITLE
is it possible to merge two records? 

### ISSUE THREAD

**Issue by jalperin** [ourresearch/total-impact-core#127]
Sometimes an article appears twice. Is it possible to merge the two records? Could it be possible?

**Comment by hpiwowar** [comment]
Hi Juan.  Nope, it isn't possible to merge articles.  The duplicate articles should be showing the same metrics.  If they aren't, click the "refresh metrics" button.  If they still aren't, let us know because you found a bug!

When they are showing the same data you can just delete one of them.  Doesn't matter which one, just click the X that appears on the left hand margin when you hover over the title name.

I'll close this ticket, but let us know if it doesn't work for you!
