### ISSUE TITLE
 isolate the watchers from the DAO, so that the unit can be tested

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#27]
isolate the watchers from the DAO, so that the unit can be tested.

**Comment by richard-jones** [comment]
Done.

In particular the Query object extends the DAO which caused problems with testing.

Note to self: shut down couch before running tests, otherwise leaks from the unit to other parts of the app (e.g the DAO) might go unnoticed.

Mocking out the DAO can be done like this:

```
import totalimpact.dao
class DAOMock(object):
    pass
# this mock is reset in the tearDown method
old_dao = totalimpact.dao.Dao
totalimpact.dao.Dao = DAOMock
```

Don't forget to tearDown the mock later
