### ISSUE TITLE
test_09_get_providers failing

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#28]
test_09_get_providers is failing.  

It seems that it is getting mock Provider objects, even though mock Provider aren't defined in Test_Provider.  

Any chance it is getting them from test_14_backend?  When I comment out 

```
ProviderFactory.get_providers = classmethod(get_providers_mock)
```

in the test_backend file, test_09_get_providers starts to work.  ?.

**Comment by richard-jones** [comment]
Hm, possibly.  It depends on what the scope of the python run time is under nose.  I assumed that each test would be isolated, but that might be a faulty assumption.  I'll look into it now ...

**Comment by richard-jones** [comment]
Ok, this is fixed.  The issue was that the nosetests environment uses the same python runtime for each test suite (which I suppose is reasonable), meaning that monkey-patching globals (like the total impact module) bleeds between tests.  I have gone through all the tests which use monkey-patches and added code to the tearDown and setUp methods to ensure that patches for that test suite are undone before the test ends.  We just have to remember to do this for all tests in future.
