### ISSUE TITLE
framework for secret api keys?

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#3]
What's the best way for us to store our secret api keys?  

Do we want to use an encryption method like we did in PHP version, or something else?
https://github.com/mhahnel/Total-Impact/blob/master/config/build-config.sh

If something else, a pointer to an example to follow or some placeholders would be very welcome.  thanks!

**Comment by jasonpriem** [comment]
I'll setup a secrets file with the same encryption approach you link to above.

**Comment by markmacgillivray** [comment]
Not sure if this has been done yet, but it appears to be an unrequired complexity. A better approach would be not to put in secret API keys at all - they should be unique to an instance anyway, so could just be inserted on install of an instance. Keeping them out of the repo altogether avoids extra hassle. (And sharing a password to unencrypt is much the same as sharing the keys themselves)

**Comment by jasonpriem** [comment]
1. nope, not done yet.
2. agreed, secret keys are unique to instance. sample config in repo should just have blanks for secret stuff.
3. but we need a means for us to share secret keys amongst one another. We could email or Skype them back and forth, but it was time-intensive and error prone.
4. so, since we all use the repo anyway, it made sense to put _all_ the secrets in one tracked doc under just _one_ secret password.

That said, the secrets are not changing so fast any more, so I can see a lot of sense in the Skype approach for now. I'm going to leave this ticket open, but the new approach will just be to 
1. create a "config-secret" file that's not tracked, 
2. move all secret config stuff there, and 
3. skype it to anyone who needs it.

cc @hpiwowar

**Comment by kevcampb** [comment]
You could create a KeepassX file to store these, and then put it into a git repository.

For the system, putting them in a local_settings.py and then using
export TOTALIMPACT_CONFIG=config/local_settings.py 
to override the default_settings.py would surely be the best approach. We can put placeholders in default_settings.py. 

Might be useful if providers raised an error if the settings are missing, or 3rd parties will get confused if they use the codebase.
