### ISSUE TITLE
fix dao and api import dependencies

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#89]
As a workaround, dao imports directly from default_settings to avoid a circular dependency.  This is probably not what we want.

**Comment by jasonpriem** [comment]
I actually think this is a pretty ok way to do it. The alternatives are that we pass this info in as arguments (annoying; have to do it everywhere but it's always going to be the same), or pass in a config object of some kind, which we really don't need for anything else so also feels too heavy.

There's no need to change these for testing, since all the tests will use the same Couch user/pw, so having them read from a file is no big deal. This lightweight approach seems like the most sensible.

I suggest we close this ticket. It's not something that Needs To Be Fixed.

**Comment by hpiwowar** [comment]
works for me.  reminder to ourselves: if we close the ticket, remove the issue number from the code.
